[General]
http-port = 8888
dashboard-port = 8234
log-level = info

[Proxy]
Demo Proxy, http, 127.0.0.1, 7890

[Proxy Group]
Proxy, select, Demo Proxy, DIRECT, REJECT

[Rule]
DOMAIN-SUFFIX, apple.com, DIRECT
DOMAIN-KEYWORD, ads, REJECT
FINAL, Proxy

[DNS]
server = 1.1.1.1, 8.8.8.8
fake-ip = false

[MITM]
enabled = false
