[General]
http-port = 8888
dashboard-port = 8234
log-level = info

[Proxy]
Demo Proxy, http, 127.0.0.1, 7890

[Proxy Group]
Proxy, select, Demo Proxy, DIRECT, REJECT
Auto, url-test, Demo Proxy, DIRECT, url=http://cp.cloudflare.com/generate_204, interval=300, tolerance=50

[Rule]
DOMAIN-SUFFIX, apple.com, DIRECT
DOMAIN-KEYWORD, ads, REJECT
FINAL, Proxy

[DNS]
server = 1.1.1.1, 8.8.8.8
fake-ip = false

[MITM]
enabled = false
